/**
 * Mock data para desenvolvimento local.
 * Substitua por dados reais do Supabase em produção.
 */

export const MOCK_PLACES = [
  {
    id: 'mock-1',
    name: 'Cacique Chá',
    slug: 'cacique-cha',
    category: 'gastronomia',
    short_description: 'Boteco beira-mar com siri e muito axé.',
    description: 'O Cacique Chá é o boteco mais tradicional da Atalaia. Vista pro mar, mesas na areia, siri mole e música ao vivo toda semana. Vai lá uma vez e não sai mais.',
    address: 'R. Niceu Dantas, 1399 — Atalaia',
    neighborhood: 'Atalaia',
    latitude: -10.9867,
    longitude: -37.0523,
    cover_image_url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600&q=80',
    whatsapp: '+5579999990001',
    instagram: '@caciquecha',
    price_range: '$$',
    plan_tier: 'pro',
    is_published: true,
    is_featured: true,
    view_count: 2341,
    whatsapp_click_count: 187,
    tags: ['beira-mar', 'ao vivo', 'siri'],
    opening_hours: { fri: '17:00-02:00', sat: '12:00-02:00', sun: '12:00-22:00' },
  },
  {
    id: 'mock-2',
    name: 'Milagres Bar',
    slug: 'milagres-bar',
    category: 'gastronomia',
    short_description: 'Drinks autorais e quitutes no coração do Bairro 13.',
    description: 'Ambiente intimista com drinks autorais, petiscos criativos e a melhor playlist da cidade. O lugar certo pra quem quer fugir do óbvio.',
    address: 'R. Itabaianinha, 340 — Centro',
    neighborhood: 'Centro',
    latitude: -10.9115,
    longitude: -37.0516,
    cover_image_url: 'https://images.unsplash.com/photo-1574096079513-d8259312b785?w=600&q=80',
    whatsapp: '+5579999990002',
    instagram: '@milagresbar',
    price_range: '$$',
    plan_tier: 'basic',
    is_published: true,
    is_featured: false,
    view_count: 890,
    whatsapp_click_count: 64,
    tags: ['drinks', 'intimista', 'petiscos'],
    opening_hours: { wed: '18:00-00:00', thu: '18:00-00:00', fri: '18:00-02:00', sat: '16:00-02:00' },
  },
  {
    id: 'mock-3',
    name: 'Pirilampo',
    slug: 'pirilampo',
    category: 'cultura',
    short_description: 'Espaço cultural com shows, exposições e café.',
    description: 'Pirilampo é o coração cultural de Aracaju. Exposições, shows acústicos, workshops e o melhor café da cidade. Se tem algo inusitado rolando, é aqui.',
    address: 'Av. Barão de Maruim, 412 — São José',
    neighborhood: 'São José',
    latitude: -10.9180,
    longitude: -37.0630,
    cover_image_url: 'https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?w=600&q=80',
    whatsapp: '+5579999990003',
    instagram: '@pirilampoaju',
    price_range: '$',
    plan_tier: 'free',
    is_published: true,
    is_featured: false,
    view_count: 340,
    whatsapp_click_count: 22,
    tags: ['cultura', 'shows', 'exposição', 'café'],
    opening_hours: { tue: '10:00-22:00', wed: '10:00-22:00', thu: '10:00-22:00', fri: '10:00-00:00', sat: '12:00-00:00' },
  },
]

export const MOCK_EVENTS = [
  {
    id: 'mock-ev-1',
    name: 'Forró do Cacique — Sexta de Fogo',
    slug: 'forro-cacique-sexta-fogo',
    category: 'show',
    short_description: 'A noite mais quente da Atalaia. Forró pé de serra ao vivo.',
    description: 'Toda sexta o Cacique Chá vira um santuário do forró. Banda ao vivo, camarote beira-mar e aquele siri mole chegando quentinho.',
    custom_location: 'Cacique Chá — Atalaia',
    latitude: -10.9867,
    longitude: -37.0523,
    cover_image_url: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=600&q=80',
    starts_at: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(),
    ends_at: new Date(Date.now() + 9 * 60 * 60 * 1000).toISOString(),
    price_info: 'R$ 20',
    organizer_name: 'Cacique Chá',
    organizer_whatsapp: '+5579999990001',
    plan_tier: 'pro',
    is_published: true,
    is_featured: true,
    view_count: 512,
    ticket_url: null,
  },
  {
    id: 'mock-ev-2',
    name: 'Feira de Arte Urbana — Pirilampo',
    slug: 'feira-arte-urbana-pirilampo',
    category: 'cultural',
    short_description: 'Arte local, artesanato, gastronomia e música independente.',
    description: 'A feira mensal do Pirilampo reúne artistas visuais, fotógrafos, artesãos e a cena musical independente de Aracaju. Entrada gratuita.',
    custom_location: 'Pirilampo — São José',
    latitude: -10.9180,
    longitude: -37.0630,
    cover_image_url: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=600&q=80',
    starts_at: new Date(Date.now() + 26 * 60 * 60 * 1000).toISOString(),
    ends_at: new Date(Date.now() + 34 * 60 * 60 * 1000).toISOString(),
    price_info: 'Gratuito',
    organizer_name: 'Pirilampo',
    organizer_whatsapp: '+5579999990003',
    plan_tier: 'free',
    is_published: true,
    is_featured: false,
    view_count: 230,
    ticket_url: null,
  },
  {
    id: 'mock-ev-3',
    name: 'Drink & Talk — Noite de Debates no Milagres',
    slug: 'drink-talk-milagres',
    category: 'cultural',
    short_description: 'Papo aberto sobre cidade, cultura e futuro. Com drinks.',
    description: 'Um encontro mensal onde a galera de Aracaju discute ideias, projetos e a cidade que queremos. Aberto a todos. Moderado pelo Milagres Bar.',
    custom_location: 'Milagres Bar — Centro',
    latitude: -10.9115,
    longitude: -37.0516,
    cover_image_url: 'https://images.unsplash.com/photo-1529543544282-ea669407fca3?w=600&q=80',
    starts_at: new Date(Date.now() + 50 * 60 * 60 * 1000).toISOString(),
    ends_at: new Date(Date.now() + 55 * 60 * 60 * 1000).toISOString(),
    price_info: 'Gratuito',
    organizer_name: 'Milagres Bar',
    organizer_whatsapp: '+5579999990002',
    plan_tier: 'basic',
    is_published: true,
    is_featured: false,
    view_count: 190,
    ticket_url: null,
  },
]

export const MOCK_FEED = [
  {
    id: 'feed-1',
    user: { name: 'Larissa M.', avatar: 'LM' },
    type: 'checkin',
    place: MOCK_PLACES[0],
    message: 'siri perfeito como sempre 🙌',
    colados: 14,
    createdAt: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
    comments: [
      { id: 'c1', user: 'Pedro G.', text: 'to indo agora!' },
      { id: 'c2', user: 'Ana C.', text: 'guarda lugar pra gente' },
    ],
  },
  {
    id: 'feed-2',
    user: { name: 'Gabriel S.', avatar: 'GS' },
    type: 'checkin',
    event: MOCK_EVENTS[0],
    message: 'começou e já tá lotado, vim cedo haha',
    colados: 31,
    createdAt: new Date(Date.now() - 70 * 60 * 1000).toISOString(),
    comments: [
      { id: 'c3', user: 'Bruna F.', text: 'ainda tem fila?' },
    ],
  },
  {
    id: 'feed-3',
    user: { name: 'Rebeca O.', avatar: 'RO' },
    type: 'checkin',
    place: MOCK_PLACES[2],
    message: 'exposição nova no Pirilampo — recomendo demais',
    colados: 8,
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    comments: [],
  },
]
